export { FootAnkleConditions } from './pages/FootAnkleConditions'
export { HeelPainPlantarFasciitis } from './pages/HeelPainPlantarFasciitis'
export { IngrownToenailTreatment } from './pages/IngrownToenailTreatment'
export { FungalToenailTreatment } from './pages/FungalToenailTreatment'
export { DiabeticFootWoundCare } from './pages/DiabeticFootWoundCare'
export { TendonPainInjuries } from './pages/TendonPainInjuries'
export { NeuropathyTreatment } from './pages/NeuropathyTreatment'
export { PlantarWart } from './pages/PlantarWart'
export { Bunion } from './pages/Bunion'
export { CornsCalluses } from './pages/CornsCalluses'
export { FootUlcer } from './pages/FootUlcer'
export { FlatFoot } from './pages/FlatFoot'
export { ItchyFeet } from './pages/ItchyFeet'
export { ConditionDetailTemplate } from './components/ConditionDetailTemplate'

